@startuml
class VentanaPrincipal {
    + {static} LOGIN_CORRECTO:boolean
    -tienda:Tienda
    +<<create>>VentanaPrincipal():void
    ~obtenerListaCompras(CID:int):Object[][]
    ~obtenerListaLibros():Object[][]
    +obtenerDatosLibroCarrito(ISBN:long):Object[]
    ~buscarLibroActualizar():void
    + {static} guardarCarritoDeCompras(CID:int,carritoDeCompras:HashMap):void
    ~obtenerPrecioImpuesto(valorUnitario:double):double
    ~obtenerPrecioTotalProducto(valorUnitario:double,cantidad:int):double
    ~obtenerPrecioVentaTotal(model:DefaultTableModel):double
    ~agregarLibroCarrito():void
    ~ {static} obtenerTipoUsuario(correoElectronico:String):ROLES
    ~pagarEfectivo():void
    ~crearCuenta():void
    ~validarInicioSesion():void
    ~usuarioExiste():void
    ~actualizarLibro():void
    ~pagarTarjeta():void
    ~buscarLibroEliminar():void
    ~mostrarPanelLoginSignUp():void
    ~validarRegistro():void
    ~agregarLibroArchivo():void
    ~eliminarLibro():void
    -getDatosLogin():String[]
    +getDialogLoginSignUp():DialogLoginSignup
    -inicializarFrame():void
    -getDatosSignUp():Object[]
    -salirFormaSegura():void
    ~eliminarPanelLoginSignUp():void
}
class PanelHistorialCompras {
    -fuenteCabecera:Font
    -fuenteCelda:Font
    -nombreColumnas:String[]
    -model:DefaultTableModel
    -CID:int
    +<<create>>PanelHistorialCompras(ventanaPrincipal:VentanaPrincipal,CID:int):void
    -rellenarTablaCompras():void
    -getDefaultTableModel():DefaultTableModel
    -celdasFormateadas():DefaultTableCellRenderer
    -inicializarPanel():void
}
class DialogLoginSignup {
    -panelContenedor:JTabbedPane
    -fuentePestania:Font
    -fuenteLabel:Font
    -fuenteTextField:Font
    -fuenteBoton:Font
    -mensajeDeError:JLabel
    -panelLogin:JPanel
    -panelRegistro:JPanel
    -boxNombreCompleto:JTextField
    -boxCorreo:JTextField
    -boxDireccion:JTextField
    -boxTelefono:JTextField
    -boxContrasena:JPasswordField
    -passwordFieldContrasena:JPasswordField
    +<<create>>DialogLoginSignup(ventanaPrincipal:VentanaPrincipal,evento:Evento):void
    -obtenerMensajeDeError():String
    +getDatosLogin():String[]
    -lambda$agregarRegistro$0(arg0:JCheckBox,arg1:ActionEvent):void
    -agregarRegistro():void
    +getDatosRegistro():Object[]
    -lambda$agregarLogin$0(arg0:JCheckBox,arg1:ActionEvent):void
    -validarCampoCorreo(boxCorreo:JTextField):void
    -lambda$agregarRegistro$1(arg0:JButton,arg1:ActionEvent):void
    -agregarLogin():void
}
class PanelCarrito {
    - {static} identificadorCarrito:int
    -nombreColumnas:String[]
    -carritoDeCompras:HashMap
    -fuenteCabecera:Font
    -fuenteCelda:Font
    -fuenteBoton:Font
    -botonPagarEfectivo:JButton
    -botonPagarTarjeta:JButton
    +model:DefaultTableModel
    -labelTotal:JLabel
    +<<create>>PanelCarrito(ventanaPrincipal:VentanaPrincipal,evento:Evento):void
    -inicializarPanelFooter():void
    +getDefaultTableModel():DefaultTableModel
    -formatearColumnas(tableCarrito:JTable):void
    -celdasDoubleFormateadas():DefaultTableCellRenderer
    -lambda$modificacionesCarrito$0(arg0:DefaultTableModel,arg1:TableModelEvent):void
    +getCarritoDeComprasTemporal():HashMap
    -descartarDelCarrito(model:DefaultTableModel,fila:int):void
    -inicializarPanelCarrito():void
    -obtenerPrecioVenta(valorUnitario:double,cantidad:int):double
    ~agregarArticulo(ISBN:long):void
    -actualizarPrecioTotal():void
    ~incrementarCantidad(ISBN:Long):void
    -actualizarCarrito(model:DefaultTableModel):void
    + {static} setIdentificadorCarrito(paramIdentificadorCarrito:int):void
    -obtenerCantidadLibro(ISBN:long):int
    +actualizarCarritoArchivo():void
    -modificacionesCarrito(model:DefaultTableModel):void
    -obtenerPrecioImpuesto(valorUnitario:double):double
    -sumarAlCarrito(model:DefaultTableModel,fila:int):void
    -quitarAlCarrito(model:DefaultTableModel,fila:int):void
    -formatearArticulo(ISBN:long):Object[]
}
class PanelEliminarLibro {
    -botonEliminar:JButton
    -fuenteLabel:Font
    -fuenteTextField:Font
    -fuenteBoton:Font
    -mensajeDeError:JLabel
    -panelCampos:JPanel
    -panelFooter:JPanel
    -boxISBN:JTextField
    -boxTitulo:JTextField
    -boxAutor:JTextField
    -boxAnioPublicacion:JTextField
    -boxGenero:JTextField
    -boxEditorial:JTextField
    +<<create>>PanelEliminarLibro(evento:Evento):void
    ~setMensajeDeError(mensaje:String):void
    -inicializarPanelCampos():void
    -inicializarPanelFooter():void
    -obtenerMensajeDeError():String
    ~validarSesionIniciada():void
    -inicializarPanel():void
    -lambda$inicializarPanelFooter$0(arg0:ActionEvent):void
    ~getISBN():long
    ~setDatosLibro(datos:Object[]):void
}
class PanelLibros {
    -nombreColumnas:String[]
    -fuenteCabecera:Font
    -fuenteCelda:Font
    -fuenteBoton:Font
    -model:DefaultTableModel
    +<<create>>PanelLibros(ventana:VentanaPrincipal,evento:Evento):void
    +getTableModel():DefaultTableModel
    -getDefaultTableModel():DefaultTableModel
    -formatearColumnas(tableLibros:JTable):void
    -celdasDoubleFormateadas():DefaultTableCellRenderer
    -inicializarPanelLibros():void
    -refrescarLista():void
}
class Evento {
    +<<create>>Evento(ventana:VentanaPrincipal):void
    +actionPerformed(e:ActionEvent):void
}
class PantallaPrincipal {
    -fuentePestania:Font
    -panelPrincipal:JTabbedPane
    +<<create>>PantallaPrincipal(ventana:VentanaPrincipal,evento:Evento):void
    -inicializarPanelLibros(ventana:VentanaPrincipal):void
    -inicializarPanelHistorialCompras():void
    -activarFuncionalidadBotones():void
    -inicalizarPanelesAdministrador():void
    -inicializarPanelCarrito():void
    -inicializarPanelPerfil():void
    +agregarPanelesSegunRol(rol:String):void
    ~iniciarSesion(datosUsuario:Object[]):void
    ~getPanelActualizarLibro():PanelActualizarLibro
    ~getDatosLibroNuevo():Object[]
    ~getPanelCarrito():PanelCarrito
    ~getPanelEliminarLibro():PanelEliminarLibro
    ~getPanelCrearCuentas():PanelCrearCuentas
    ~getPanelLibros():PanelLibros
}
class Main {
    +<<create>>Main():void
    + {static} main(args:String[]):void
}
class PanelCrearCuentas {
    -botonValidar:JButton
    -botonCrearCuenta:JButton
    -fuenteLabel:Font
    -fuenteTextField:Font
    -fuenteBoton:Font
    -panelDatos:JPanel
    -panelFooter:JPanel
    -boxCorreo:JTextField
    -boxClave:JTextField
    -boxNombre:JTextField
    -boxDireccion:JTextField
    -boxTelefono:JTextField
    -mensajeDeError:JLabel
    +<<create>>PanelCrearCuentas(evento:Evento):void
    +setMensajeDeError(mensaje:String):void
    +getDatosUsuario():Object[]
    -inicializarPanelCampos():void
    -inicializarPanelFooter():void
    -obtenerMensajeDeError():String
    ~validarSesionIniciada():void
    -inicializarPanel():void
    +getCorreo():String
}
class PanelAgregarLibro {
    -botonGuardar:JButton
    -fuenteLabel:Font
    -fuenteTextField:Font
    -fuenteBoton:Font
    -FORMATOS:String[]
    -comboBoxFormato:JComboBox
    -mensajeDeError:JLabel
    -panelCampos:JPanel
    -panelFooter:JPanel
    -boxISBN:JTextField
    -boxTitulo:JTextField
    -boxAutor:JTextField
    -boxAnioPublicacion:JTextField
    -boxGenero:JTextField
    -boxEditorial:JTextField
    -boxNumPaginas:JTextField
    -boxPrecioVenta:JTextField
    -boxCantidadInventario:JTextField
    +<<create>>PanelAgregarLibro(evento:Evento):void
    -inicializarPanelCampos():void
    -inicializarPanelFooter():void
    -obtenerMensajeDeError():String
    ~validarSesionIniciada():void
    -inicializarPanel():void
    -lambda$inicializarPanelFooter$0(arg0:ActionEvent):void
    ~getDatosLibro():Object[]
}
class PanelPerfil {
    -botonGuardar:JButton
    -boxNombreCompleto:JTextField
    -boxCorreo:JTextField
    -boxDireccion:JTextField
    -boxTelefono:JTextField
    -fuenteLabel:Font
    -fuenteTextField:Font
    -fuenteBoton:Font
    -mensajeDeError:JLabel
    -datosUsuario:Object[]
    -nombreCompleto:String
    -correoElectronico:String
    -direccion:String
    -telefono:long
    -tipoUsuario:ROLES
    -CID:int
    -labelTipoUsuarioActual:JLabel
    -boxContrasena:JPasswordField
    +<<create>>PanelPerfil(pantallaPrincipal:PantallaPrincipal,evento:Evento):void
    -inicializarPanelFooter():void
    -obtenerMensajeDeError():String
    ~validarSesionIniciada():void
    -lambda$inicializarPanelDatosUsuario$0(arg0:JCheckBox,arg1:ActionEvent):void
    -inicializarPanelDatosUsuario():void
    -lambda$inicializarPanelFooter$0(arg0:ActionEvent):void
    +getCID():int
    -inicializarPanelPerfil():void
    -refrescarDatosPerfil(datosUsuario:Object[]):void
    -rellenarDatosVacios():void
    +setDatosUsuario(datosUsuario:Object[]):void
}
class PanelActualizarLibro {
    -botonBuscar:JButton
    -botonGuardar:JButton
    -fuenteLabel:Font
    -fuenteTextField:Font
    -fuenteBoton:Font
    -comboBoxFormato:JComboBox
    -mensajeDeError:JLabel
    -panelCampos:JPanel
    -panelFooter:JPanel
    -boxISBN:JTextField
    -boxTitulo:JTextField
    -boxAutor:JTextField
    -boxAnioPublicacion:JTextField
    -boxGenero:JTextField
    -boxEditorial:JTextField
    -boxNumPaginas:JTextField
    -boxPrecioVenta:JTextField
    -boxCantidadInventario:JTextField
    +<<create>>PanelActualizarLibro(evento:Evento):void
    -inicializarPanelCampos():void
    -inicializarPanelFooter():void
    -obtenerMensajeDeError():String
    ~validarSesionIniciada():void
    -inicializarPanel():void
    -lambda$inicializarPanelFooter$0(arg0:ActionEvent):void
    -lambda$inicializarPanelFooter$1(arg0:ActionEvent):void
    +getISBN():long
    ~setDatosLibro(datos:Object[]):void
    +getDatosLibro():Object[]
}

VentanaPrincipal --> "1" Evento
VentanaPrincipal --> "1" DialogLoginSignup
VentanaPrincipal --> "1" PantallaPrincipal
PanelHistorialCompras --> "1" VentanaPrincipal
DialogLoginSignup --> "1" Evento
DialogLoginSignup ..> VentanaPrincipal
PanelCarrito --> "1" Evento
PanelCarrito --> "1" VentanaPrincipal
PanelEliminarLibro --> "1" Evento
PanelLibros --> "1" Evento
PanelLibros --> "1" VentanaPrincipal
Evento --> "1" VentanaPrincipal
PantallaPrincipal --> "1" Evento
PantallaPrincipal --> "1" VentanaPrincipal
PantallaPrincipal --> "1" PanelLibros
PantallaPrincipal --> "1" PanelCarrito
PantallaPrincipal --> "1" PanelPerfil
PantallaPrincipal --> "1" PanelAgregarLibro
PantallaPrincipal --> "1" PanelActualizarLibro
PantallaPrincipal --> "1" PanelEliminarLibro
PantallaPrincipal --> "1" PanelCrearCuentas
PantallaPrincipal --> "1" PanelHistorialCompras
PanelCrearCuentas --> "1" Evento
PanelAgregarLibro --> "1" Evento
PanelPerfil --> "1" Evento
PanelPerfil --> "1" PantallaPrincipal
PanelActualizarLibro --> "1" Evento

@enduml